"""re-arranged theme field

Revision ID: 1a7282a895ee
Revises: 663e8e11aace
Create Date: 2025-10-20 17:25:29.597587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a7282a895ee'
down_revision: Union[str, Sequence[str], None] = '663e8e11aace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_credentials', sa.Column('theme', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('integrations', 'theme')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('theme', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('app_credentials', 'theme')
    # ### end Alembic commands ###
