"""usage column added

Revision ID: 3818894fb83e
Revises: 1ae1408007ad
Create Date: 2025-10-20 18:23:53.918523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3818894fb83e'
down_revision: Union[str, Sequence[str], None] = '1ae1408007ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('usage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrations', 'usage')
    # ### end Alembic commands ###
