"""added schema desrription feild

Revision ID: 4d6f696f76ba
Revises: 8b9df4b64565
Create Date: 2025-10-13 18:43:33.126526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d6f696f76ba'
down_revision: Union[str, Sequence[str], None] = '8b9df4b64565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema_specifications', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schema_specifications', 'description')
    # ### end Alembic commands ###
