"""added free trail feature on subscription

Revision ID: 4e8fcccb5f77
Revises: m1merge_abdddf_f6a9
Create Date: 2025-11-12 10:57:09.468931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8fcccb5f77'
down_revision: Union[str, Sequence[str], None] = 'm1merge_abdddf_f6a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column('launch_tokens', 'passthrough')
#     op.add_column('subscriptions', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column('subscriptions', 'trial_ends_at')
#     op.add_column('launch_tokens', sa.Column('passthrough', sa.TEXT(), autoincrement=False, nullable=True))
#     # ### end Alembic commands ###
