"""added credentials and integration

Revision ID: 663e8e11aace
Revises: a4b85657275c
Create Date: 2025-10-19 20:24:30.396843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '663e8e11aace'
down_revision: Union[str, Sequence[str], None] = 'a4b85657275c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('client_secret_hash', sa.String(), nullable=False),
    sa.Column('client_secret_expires_at', sa.DateTime(), nullable=True),
    sa.Column('app_name', sa.String(), nullable=False),
    sa.Column('authorized_js_origins', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'app_name', name='uq_app_credentials_account_app_name'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('schema_id', sa.UUID(), nullable=False),
    sa.Column('redirect_url', sa.String(), nullable=True),
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('api_endpoint', sa.String(), nullable=True),
    sa.Column('api_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('behavior', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('theme', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['credential_id'], ['app_credentials.id'], ),
    sa.ForeignKeyConstraint(['schema_id'], ['schema_specifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('integrations')
    op.drop_table('app_credentials')
    # ### end Alembic commands ###
