"""add email_verifications table

Revision ID: 8b9df4b64565
Revises: 8f51110aabf8
Create Date: 2025-10-02 13:07:39.008806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b9df4b64565'
down_revision: Union[str, Sequence[str], None] = '8f51110aabf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('manage_schema_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('memberships', sa.Column('manage_schema_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('schema_specifications', sa.Column('account_id', sa.UUID(), nullable=False))
    op.add_column('schema_specifications', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_schema_specifications_account_id'), 'schema_specifications', ['account_id'], unique=False)
    op.create_index(op.f('ix_schema_specifications_created_by_user_id'), 'schema_specifications', ['created_by_user_id'], unique=False)
    op.create_foreign_key(None, 'schema_specifications', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'schema_specifications', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schema_specifications', type_='foreignkey')
    op.drop_constraint(None, 'schema_specifications', type_='foreignkey')
    op.drop_index(op.f('ix_schema_specifications_created_by_user_id'), table_name='schema_specifications')
    op.drop_index(op.f('ix_schema_specifications_account_id'), table_name='schema_specifications')
    op.drop_column('schema_specifications', 'created_by_user_id')
    op.drop_column('schema_specifications', 'account_id')
    op.drop_column('memberships', 'manage_schema_ids')
    op.drop_column('invitations', 'manage_schema_ids')
    # ### end Alembic commands ###
