"""deleted at feild

Revision ID: a43e4252d299
Revises: e11b657e913c
Create Date: 2025-10-13 22:44:20.316713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43e4252d299'
down_revision: Union[str, Sequence[str], None] = 'e11b657e913c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema_specifications', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schema_specifications', 'deleted_at')
    # ### end Alembic commands ###
