"""simple change on account

Revision ID: a4b85657275c
Revises: db2657184bfd
Create Date: 2025-10-17 22:45:48.898597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b85657275c'
down_revision: Union[str, Sequence[str], None] = 'db2657184bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_account_owner', 'accounts', ['owner_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_account_owner', 'accounts', type_='unique')
    # ### end Alembic commands ###
