"""add integration_logs table

Revision ID: abdddf59158b
Revises: 05a79ac796bc
Create Date: 2025-10-24 22:07:33.888819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abdddf59158b'
down_revision: Union[str, Sequence[str], None] = '05a79ac796bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('schema_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('integration_name', sa.String(), nullable=True),
    sa.Column('schema_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=True),
    sa.Column('rows_failed', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('request_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_logs_account_id'), 'integration_logs', ['account_id'], unique=False)
    op.create_index(op.f('ix_integration_logs_integration_id'), 'integration_logs', ['integration_id'], unique=False)
    op.create_index(op.f('ix_integration_logs_schema_id'), 'integration_logs', ['schema_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_logs_schema_id'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_integration_id'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_account_id'), table_name='integration_logs')
    op.drop_table('integration_logs')
    # ### end Alembic commands ###
